### PR TITLE
Add two strategies for disabling the client

### PR DESCRIPTION
**Pull request by oliverwoodings**
@tcolgate thoughts?

### CODE REVIEW

**Comment by swagatha-christie** [comment]
By analyzing the blame information on this pull request, we identified @SimenB, @siimon and @pnieuwenhuis to be potential reviewers

**Comment by tcolgate** [comment]
Looks reasonable to me. @lclarkmichalek any thoughts?

**Comment by SimenB** [comment]
Nice bot guys 😆 

Although I like this change, any chance of it being a PR upstream? 😄

**Comment by oliverwoodings** [comment]
@SimenB sorry for the disturbance! We need to tweak the settings a little haha

We've made quite a few changes to our fork, I'll talk to Tristan about which ones we can propagate upstream.

**Comment by tcolgate** [comment]
@SimenB once we merge it on this side, I'll try rebasing it on upstream and if it applies cleanly, I'll raise a PR.

We've got a bunch of stuff in this fork now that I don't think would be generally desirable)

**Comment by lclarkmichalek** [comment]
LGMT

**Pull request merged**
